### ISSUE TITLE
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigationcore/navigation/3.0.2/navigation-3.0.2.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by saeedahmed2023** [pawan-pk/react-native-mapbox-navigation#10]
<img width="1426" alt="Screenshot 2024-08-23 at 4 13 38 AM" src="https://github.com/user-attachments/assets/be2782dd-8039-4f00-a13d-02b66fa48eef">

error on     "react-native": "0.75.1"

**Comment by pawan-pk** [comment]
Follow [Android Specific Instructions](https://github.com/pawan-pk/react-native-mapbox-navigation?tab=readme-ov-file#android-specific-instructions) and add your private mapbox access token.
