### ISSUE TITLE
Measurement system issue

### ISSUE THREAD

**Issue by Nocolais95** [pawan-pk/react-native-mapbox-navigation#11]
Hi my friend.

I've faced this issue while testing. I´m from Argentina and my country uses the metric system as the measurement system (m, km, etc.)

When I set language in 'es-ES', it works correctly, but the measurement system it uses is Android's. Actually, if I set it to Spanish (US), it defaults to the imperial system used there (feet, yards, etc.).

It should use the metric system based on the language I provide.

A possible solution could be to make the bottom banner, where this data is displayed, optional with a boolean.

![16830b0b-fae1-49df-aa02-927c9c0d5c64](https://github.com/user-attachments/assets/7d82cea3-a510-424a-b388-5c8294eaaf1b)

![9462a13b-482c-419d-8676-1eb99094a9ff](https://github.com/user-attachments/assets/97b461c2-65ef-40dd-b49a-9a601ca6e845)

**Comment by Shahbaz334** [comment]
hi brother how you can solve this issue onm android 
<img width="736" alt="Screenshot 2024-08-23 at 1 21 17 AM" src="https://github.com/user-attachments/assets/50b275f5-b267-472b-83c9-ecc9884596bf">
Received status code 401 from server: Unauthorized

**Comment by pawan-pk** [comment]
> hi brother how you can solve this issue onm android <img alt="Screenshot 2024-08-23 at 1 21 17 AM" width="736" src="https://private-user-images.githubusercontent.com/68393927/360663879-50b275f5-b267-472b-83c9-ecc9884596bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTAwNDgsIm5iZiI6MTcyNDM4OTc0OCwicGF0aCI6Ii82ODM5MzkyNy8zNjA2NjM4NzktNTBiMjc1ZjUtYjI2Ny00NzJiLTgzYzktZWNjOTg4NDU5NmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA1MDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGNmYWQ0NTM3YTA1ZGY0NWRmOGI1NTkzZTBjOWJhZDVlNjhiYWZiMTJhMTg3ZDBlZWYzOWM3MzMwMGFiNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bs5CulNHAuzAUm5Ew6WmcPdAirhKg3Z1vom5xtg9CQQ"> Received status code 401 from server: Unauthorized

See [Issue-10](https://github.com/pawan-pk/react-native-mapbox-navigation/issues/10)

**Comment by LeonSoler** [comment]
i would also like this feature!

**Comment by LeonSoler** [comment]
> Hi my friend.
> 
> I've faced this issue while testing. I´m from Argentina and my country uses the metric system as the measurement system (m, km, etc.)
> 
> When I set language in 'es-ES', it works correctly, but the measurement system it uses is Android's. Actually, if I set it to Spanish (US), it defaults to the imperial system used there (feet, yards, etc.).
> 
> It should use the metric system based on the language I provide.
> 
> A possible solution could be to make the bottom banner, where this data is displayed, optional with a boolean.
> 
> ![16830b0b-fae1-49df-aa02-927c9c0d5c64](https://private-user-images.githubusercontent.com/89423783/360635238-7d82cea3-a510-424a-b388-5c8294eaaf1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDU4NTksIm5iZiI6MTcyNTkwNTU1OSwicGF0aCI6Ii84OTQyMzc4My8zNjA2MzUyMzgtN2Q4MmNlYTMtYTUxMC00MjRhLWIzODgtNWM4Mjk0ZWFhZjFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDVlM2I1MTViNDRjZDM2YzdjMDIzMTBhNGZjMWYzZWEwNDE3MzA0ODJjMDVhNzAxNTg5ZDI0MmFkZDIxZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2GydM9i6gBMd3Soa3Ff1B17MMkoB7_bCMdlOPiLQu8)
> 
> ![9462a13b-482c-419d-8676-1eb99094a9ff](https://private-user-images.githubusercontent.com/89423783/360635427-97b461c2-65ef-40dd-b49a-9a601ca6e845.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDU4NTksIm5iZiI6MTcyNTkwNTU1OSwicGF0aCI6Ii84OTQyMzc4My8zNjA2MzU0MjctOTdiNDYxYzItNjVlZi00MGRkLWI0OWEtOWE2MDFjYTZlODQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZGZjYzNkNzMxZmY2NDBlYmEyNDg3OWYwNjYyMWQ5MTk1YzYwYjM4NTc5YjBmYTc4ZDEzYzQwZmUwMzkzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyaKyRClOEPmD4oium9kPOTw4fajgzg_RpGWrwPjjq0)

![image](https://github.com/user-attachments/assets/efd0828c-2e14-4d4d-9413-d0fee2f13511)

If you change the emulators language to spanish-AR it will automatically trigger the units into metric units

**Comment by Nocolais95** [comment]
> > Hi my friend.
> > I've faced this issue while testing. I´m from Argentina and my country uses the metric system as the measurement system (m, km, etc.)
> > When I set language in 'es-ES', it works correctly, but the measurement system it uses is Android's. Actually, if I set it to Spanish (US), it defaults to the imperial system used there (feet, yards, etc.).
> > It should use the metric system based on the language I provide.
> > A possible solution could be to make the bottom banner, where this data is displayed, optional with a boolean.
> > ![16830b0b-fae1-49df-aa02-927c9c0d5c64](https://private-user-images.githubusercontent.com/89423783/360635238-7d82cea3-a510-424a-b388-5c8294eaaf1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDU4NTksIm5iZiI6MTcyNTkwNTU1OSwicGF0aCI6Ii84OTQyMzc4My8zNjA2MzUyMzgtN2Q4MmNlYTMtYTUxMC00MjRhLWIzODgtNWM4Mjk0ZWFhZjFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDVlM2I1MTViNDRjZDM2YzdjMDIzMTBhNGZjMWYzZWEwNDE3MzA0ODJjMDVhNzAxNTg5ZDI0MmFkZDIxZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2GydM9i6gBMd3Soa3Ff1B17MMkoB7_bCMdlOPiLQu8)
> > ![9462a13b-482c-419d-8676-1eb99094a9ff](https://private-user-images.githubusercontent.com/89423783/360635427-97b461c2-65ef-40dd-b49a-9a601ca6e845.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDU4NTksIm5iZiI6MTcyNTkwNTU1OSwicGF0aCI6Ii84OTQyMzc4My8zNjA2MzU0MjctOTdiNDYxYzItNjVlZi00MGRkLWI0OWEtOWE2MDFjYTZlODQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZGZjYzNkNzMxZmY2NDBlYmEyNDg3OWYwNjYyMWQ5MTk1YzYwYjM4NTc5YjBmYTc4ZDEzYzQwZmUwMzkzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyaKyRClOEPmD4oium9kPOTw4fajgzg_RpGWrwPjjq0)
> 
> ![image](https://private-user-images.githubusercontent.com/42130279/365763825-efd0828c-2e14-4d4d-9413-d0fee2f13511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTIyMzEsIm5iZiI6MTcyNTkxMTkzMSwicGF0aCI6Ii80MjEzMDI3OS8zNjU3NjM4MjUtZWZkMDgyOGMtMmUxNC00ZDRkLTk0MTMtZDBmZWUyZjEzNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE5NTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOWEzMzQ2MjE1NGVlMmE2MTNmMGQyODRhMTA0YWMzNjFmZDlhNmJmODlkMWUwZDhhNTY3OTQyZjA1ZTEzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1qdPWf0MiE7itFgp3aLgDJoNLNYR1PzTPZQV7U5EmA)
> 
> If you change the emulators language to spanish-AR it will automatically trigger the units into metric units



Thanks, my friend. Where can I change the language?

The first and second images cannot be viewed.

**Comment by pawan-pk** [comment]
@Nocolais95 
Added Requested support [Release 0.4.1](https://github.com/pawan-pk/react-native-mapbox-navigation/compare/v0.3.2...v0.4.1) (2024-09-09)
