### ISSUE TITLE
Expo Prebuild

### ISSUE THREAD

**Issue by syedmumersajjad** [pawan-pk/react-native-mapbox-navigation#13]
Incident Identifier: BAD0009B-86D5-4761-898E-42942AA1EF8D
CrashReporter Key: 91FE9550-7974-8D4E-BC06-971601F52573
Hardware Model: MacBookPro16,2

Coalition: com.apple.CoreSimulator.SimDevice.B8C8F3B3-9BAA-4799-9EDD-A2FD5439F7AC [24256]
Responsible Process: SimulatorTrampoline [51232]

Date/Time: 2024-08-25 14:46:31.2490 +0500
Launch Time: 2024-08-25 14:46:31.1987 +0500
OS Version: macOS 14.6.1 (23G93)
Release Type: User
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/MapboxCommon.framework/MapboxCommon
Referenced from: <6645BACD-586B-3B2C-A884-09B701040564> /Users/USER/Library/Developer/CoreSimulator/Devices/B8C8F3B3-9BAA-4799-9EDD-A2FD5439F7AC/data/Containers/Bundle/Application/8AFF4689-0E88-4190-85AE-614DC219379F/YurDrivers.app/YurDrivers
Reason: tried: '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/MapboxCommon.framework/MapboxCommon' (no such file), '/usr/lib/swift/MapboxCommon.framework/MapboxCommon' (no such file, not in dyld cache), '/Users/mac/Library/Developer/CoreSimulator/Devices/B8C8F3B3-9BAA-4799-9EDD-A2FD5439F7AC/data/Containers/Bundle/Application/8AFF4689-0E88-4190-85AE-614DC219379F/YurDrivers.app/Frameworks/MapboxCommon.framework/MapboxCommon' (no such file), '/Users/mac/Library/Developer/CoreSimulator/Devices/B8C8F3B3-9BAA-4799-9EDD-A2FD5439F7AC/data/Containers/Bundle/Application/8AFF4689-0E88-4190-85AE-614
(terminated at launch; ignore backtrace)

**Comment by jacquesngomeheffa** [comment]
@syedmumersajjad check this out https://github.com/pawan-pk/react-native-mapbox-navigation/issues/12#issuecomment-2309303069
