### ISSUE TITLE
Multiple commands product privacyInfo

### ISSUE THREAD

**Issue by RemiHin** [pawan-pk/react-native-mapbox-navigation#18]
After installing the package I ran in to an issue building my app for iOS.

Saw the same error in a different issue, but as i am not using Expo, the solution didn't work for me

`error: Multiple commands produce '/Users/[...]/Library/Developer/Xcode/DerivedData/[...]/PrivacyInfo.xcprivacy'`

I also have rnmapbox installed in my project.
My Podfile has `$RNMapboxMapsVersion = '= 10.17.0'`

Any idea's?

**Comment by RemiHin** [comment]
removed my PrivacyInfo.xcprivacy and rebuild the app, now it works... 🤷🏻 
But i'm missing my own privacyinfo, which is suboptimal

**Comment by pawan-pk** [comment]
If you encounter future issues see our example [Link](https://github.com/pawan-pk/react-native-mapbox-navigation/tree/main/example).

**Comment by cb-ksolves** [comment]
Hi @RemiHin were you able to find a solution keeping you `PrivacyInfo.xcprivacy`?

**Comment by RemiHin** [comment]
@cb-ksolves i decided to not use this package but build my own navigation.

Which solved the issue 😅

**Comment by cb-ksolves** [comment]
@RemiHin I'm also thinking the same. Thanks a lot for your quick response.
