### ISSUE TITLE
navigation back or go another screen 

### ISSUE THREAD

**Issue by Ashiq-jutt** [pawan-pk/react-native-mapbox-navigation#22]
![image](https://github.com/user-attachments/assets/bde1cecb-61de-4596-8ca3-3edfb12aa414)

**Comment by pawan-pk** [comment]
@Ashiq-jutt Fixed in [Release 0.5.2](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.5.2).
