### ISSUE TITLE
Zoom fails when the origin changes 

### ISSUE THREAD

**Issue by Nocolais95** [pawan-pk/react-native-mapbox-navigation#24]
Hi my friend, I just came across this issue.

In Android, while you are driving, the zoom fail because origin is constantly changing and the setOrigin functions calls this code

`val initialCameraOptions = CameraOptions.Builder()
      .zoom(14.0)
      .center(origin)
      .build()
    binding.mapView.mapboxMap.setCamera(initialCameraOptions)`
    
 It  will work fine if you move this code into the initNavigation function like this:
 
 `private fun initNavigation() {
    if (origin == null || destination == null) {
      sendErrorToReact("origin and destination are required")
      return
    }

    val initialCameraOptions = CameraOptions.Builder()  // <== Move here
      .zoom(14.0)
      .center(origin)
      .build()
    binding.mapView.mapboxMap.setCamera(initialCameraOptions)

    // Start Navigation
    startNavigation()
    ....`

Thanks.

**Comment by pawan-pk** [comment]
@Nocolais95, Thanks for your feedback
