### ISSUE TITLE
Custom Markers

### ISSUE THREAD

**Issue by itzik-camelot-ai** [pawan-pk/react-native-mapbox-navigation#26]
hi @pawan-pk, 
i tried to add custom markers to map like i did on rnmapbox mapboxgl
but i couldn't do so.

is there a way or a trick to succeed?
i tried creating a mapboxgl to be a transparent overlay to show the markers alone and sync its position, but it isn't working.

hopefully there will be a simple solution i missed, thanks.

**Comment by pawan-pk** [comment]
Currently, This feature is not supported, help developer by [sponsoring us](https://github.com/sponsors/pawan-pk) for continuous maintenance of open source packages.
