### ISSUE TITLE
iOS still using Mapbox Navigation v2?

### ISSUE THREAD

**Issue by ryansommers** [pawan-pk/react-native-mapbox-navigation#28]
Just wanted to confirm: the readme says this package is using Mapbox Navigation v3, but I'm seeing 2.18.1 in the iOS podspec?

It looks like version 3 isn't available via CocoaPods yet though, any plans to implement through Swift Package Manager?

**Comment by pawan-pk** [comment]
Mapbox navigation v3 sdk not suported cocoapods and react native not provided spm yet. I am planing for future major release 1.x.x that have fully functional with more features.
