### ISSUE TITLE
Expo

### ISSUE THREAD

**Issue by KindCoder-no** [pawan-pk/react-native-mapbox-navigation#31]
Do you have any good solution to run this with expo/eas? 

Since this package requires native code it will not work with expo out of the box, is there any plans to make this package compatible with expo? Or any documentation to use it in an expo application without ejecting the project

**Comment by jacquesngomeheffa** [comment]
Dear @KindCoder-no 
Check this out [https://github.com/YoussefHenna/expo-mapbox-navigation](url)

https://github.com/YoussefHenna/expo-mapbox-navigation
