### ISSUE TITLE
Mute in Android

### ISSUE THREAD

**Issue by Nocolais95** [pawan-pk/react-native-mapbox-navigation#7]
I my friend.

First of all, I have to say you that your code has been really useful.

I was able to implement it with Expo using some plugins, and it works awesomely! I would like to add this to your code.

However, I am facing an issue on Android when trying to initialize with the voice muted or just avoid voice navigation.

`<MapboxNavigation
        startOrigin={{ latitude: latOrigin, longitude: lonOrigin }}
        destination={{ latitude, longitude }}
        style={styles.containerNavigation}
        shouldSimulateRoute={false}
        showCancelButton={false}
        language="es"
        mute 
      />`
     
There is a problem when I try to set it to mute, and my app crashes immediately.

**Comment by pawan-pk** [comment]
Closing issue behalf of fixed in [Release v0.3.2](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.3.2)
