### ISSUE TITLE
Android: The route is not created and is zoomed out by default on launch.

### ISSUE THREAD

**Issue by aaron038** [pawan-pk/react-native-mapbox-navigation#9]
Great work! It seems to be working well on iOS, but I'm encountering the following issue with the example app on Android:

The route isn't being created between the source and destination, and the map is zoomed out by default. I've attached a screen recording for reference.

Is there anything additional that needs to be done beyond what's in the installation guide?

![Screenshot 2024-08-22 at 11 56 14 AM](https://github.com/user-attachments/assets/9e429429-55dd-4cda-bee6-2bcf2d889da6)

![Screenshot 2024-08-22 at 11 59 27 AM](https://github.com/user-attachments/assets/b13e6d61-860c-4c18-a953-9346dedd8063)

**Comment by saeedahmed2023** [comment]
what react native version you are using and android studio version for android

**Comment by aaron038** [comment]
> what react native version you are using and android studio version for android

I'm running the example app of the project using React Native version 0.74.3.

For Android development, I'm using Android Studio Jellyfish | 2023.3.1 Patch 1, with the following details:
Build: #AI-233.14808.21.2331.11842104, built on May 14, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
OS: macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering: ON
Registry setting: ide.experimental.ui=true

**Comment by pawan-pk** [comment]
Fixed in [Release 0.4.1](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.4.1)
